name: app_agrigeo
description: "Application mobile pour la gestion agricole intelligente avec IA et cartographie."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4


  # ðŸ—ºï¸ Cartographie
  google_maps_flutter: ^2.6.0
  geolocator: ^13.0.3
  flutter_map: ^6.1.0
  geocoding: ^3.0.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.1.0

  # ðŸ“¸ Gestion mÃ©dias
  image_picker: ^1.0.4
  image: ^4.5.4
  file_picker: ^10.0.0
  csv: ^6.0.0  # Mise Ã  jour majeure recommandÃ©e
  flutter_svg: ^2.0.7

  # ðŸ¤– IA
  dart_openai: ^5.0.0
  tflite_flutter: ^0.11.0
  camera: ^0.11.1

  # ðŸŽ¨ UI & Animations
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.1.1+1
  lottie: ^3.0.0
  rive: ^0.13.20
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1  # Mise Ã  jour majeure
  carousel_slider: ^5.0.0  # Mise Ã  jour majeure
  percent_indicator: ^4.2.2

  # ðŸ“¡ Communication
  http: ^1.1.0
  dio: ^5.3.2
  socket_io_client: ^3.1.1
  flutter_chat_ui: ^1.6.0

  # ðŸ§  State & Storage
  provider: ^6.1.4
  shared_preferences: ^2.2.2

  # ðŸ”” Notifications
  flutter_local_notifications: ^19.0.0

  # ðŸ“Š Data Viz
  syncfusion_flutter_charts: ^29.1.33
  intl: ^0.18.0

  # ðŸŒ Utilitaires
  url_launcher: ^6.2.6
  form_validator: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.10.0
  printing: ^5.9.1
  
  path_provider: ^2.1.1

  # ðŸ¤– Google Generative AI
  google_generative_ai: ^0.2.0

  # ðŸŒ WebView
  webview_flutter: ^4.0.0

  # ðŸŒ WebView Android
  webview_flutter_android: ^3.0.0

  # ðŸŒ WebView WKWebview
  webview_flutter_wkwebview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:

    - lib/assets/images/fao_logo.png
    - lib/assets/images/ci_logo.png
    - lib/assets/images/afd_logo.png
    - lib/assets/images/cnra_logo.png
    - lib/assets/animations/ai_analysis.json
    - 'lib/assets/images/farm_bg.jpg'
    - 'lib/assets/images/Registerimg.png'
    - 'lib/assets/images/rgstimg.png'
    - lib/assets/images/logo.png

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  geolocator_android: ^5.0.1
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  unicode: ^1.1.8
  vm_service: ^15.0.0